-- Create STUDENT table if not exists
CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(100),
    CITY VARCHAR(100),
    MARKS INT DEFAULT 0,
    GRADE CHAR(1) DEFAULT 'N'
);

-- Insert dummy data if empty
INSERT IGNORE INTO STUDENT (ROLL_NO, NAME, EMAIL, PASSWORD, CITY, MARKS, GRADE)
VALUES (101, 'Test Student', 'student@test.com', 'password123', 'New York', 85, 'A');
